package com.final_project_college.connection;

import com.final_project_college.exception.DataAccessException;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ConnectionWrapper implements AutoCloseable {

    private final Connection connection;

    public ConnectionWrapper(Connection connection) {
        this.connection = connection;
    }

    public PreparedStatement prepareStatement(String statement) throws SQLException {
        return connection.prepareStatement(statement);
    }

    public PreparedStatement prepareStatement(String statement, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(statement, autoGeneratedKeys);
    }

    public Connection getConnection() {
        return connection;
    }

    public void close() throws SQLException, DataAccessException {
        if (connection.getAutoCommit()) connection.close();
        else throw new DataAccessException("Transaction does not finish.");
    }
}